### ISSUE TITLE
Apache server - Forbidden access

### ISSUE THREAD

**Issue by antowan** [pnglabz/docker-compose-lamp#3]
I have the following error message from the Apache server just after running the containers.
Once I connect in the browser to the localhost.

```
Forbidden
You don't have permission to access / on this server.
```

I have changed the permission and ownership of the /var/www/html folder within the container to www-data but the issue persists. 

Do you have any workaround ?
Thank you for your help.

**Comment by narendravaghela** [comment]
It should work without any issue. On which platform are you trying this stack?

**Comment by antowan** [comment]
In am running Docker (Docker version 18.03.1-ce) on Windows 10.
When I check the docker container logs for the web server I have no specific error.
Just the following but it is not related.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.5. Set the 'ServerName' directive globally to suppress this message

Any .htaccess or user permission file that should be changed ?
Thank you.

**Comment by narendravaghela** [comment]
Nothing should be changed. Can you check that there is no other apache2 in your system? Or may be another application which uses the same address and port?

**Comment by antowan** [comment]
Well I still have the issue on my docker installation on Windows, I will try later if I can on a Linux based machine.
Thank you anyway for your replies.

**Comment by MahbbRah** [comment]
Docker Windows 10 WSL backend, updated file/folder permission but still the issue exists.
